#!/usr/bin/env node
/* Converts the scrollmapper KJV JSON into src/data/kjv.js — a plain JS file
   assigning a `KJV` global structured book id -> chapters -> verses, keyed to
   the book ids in src/data/core.js. A JS file (not fetched JSON) so the game
   still works when dist/bible-quest.html is opened directly from disk.

   Usage:
     node tools/build-bible.js [path-to-KJV.json]

   Without an argument it looks for tools/KJV.json, then tries to download
   https://raw.githubusercontent.com/scrollmapper/bible_databases/master/formats/json/KJV.json
   (in proxied environments, download that file yourself and pass its path).

   The KJV (1769) text is public domain. */
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
const SOURCE_URL = 'https://raw.githubusercontent.com/scrollmapper/bible_databases/master/formats/json/KJV.json';

async function loadSource() {
  const arg = process.argv[2];
  const candidates = [arg, path.join(__dirname, 'KJV.json')].filter(Boolean);
  for (const c of candidates) {
    if (fs.existsSync(c)) return JSON.parse(fs.readFileSync(c, 'utf8'));
  }
  console.log('No local KJV.json found, downloading from scrollmapper/bible_databases…');
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error('download failed (' + res.status + ') — fetch ' + SOURCE_URL + ' manually and pass its path');
  return res.json();
}

(async () => {
  const src = await loadSource();

  /* Book ids come from core.js itself so the two can never drift. */
  const BOOKS = eval(fs.readFileSync(path.join(root, 'src/data/core.js'), 'utf8') + ';BOOKS');
  if (src.books.length !== BOOKS.length) {
    throw new Error(`source has ${src.books.length} books, core.js has ${BOOKS.length}`);
  }

  const out = {};
  src.books.forEach((book, i) => {
    const meta = BOOKS[i]; // both lists are in canonical order
    if (book.chapters.length !== meta.ch) {
      throw new Error(`${meta.id} (${book.name}): ${book.chapters.length} chapters in source, core.js says ${meta.ch}`);
    }
    out[meta.id] = book.chapters.map((c, ci) => {
      if (c.chapter !== ci + 1) throw new Error(`${meta.id} chapter ${c.chapter} out of order`);
      return c.verses.map((v, vi) => {
        if (v.verse !== vi + 1) throw new Error(`${meta.id} ${c.chapter}:${v.verse} out of order`);
        if (!v.text || !v.text.trim()) throw new Error(`${meta.id} ${c.chapter}:${v.verse} empty`);
        return v.text.trim();
      });
    });
  });

  const verses = Object.values(out).reduce((n, b) => n + b.reduce((m, c) => m + c.length, 0), 0);
  const body = `/* Generated by tools/build-bible.js — do not edit by hand.
   King James Version (1769), public domain. Source: scrollmapper/bible_databases.
   ${BOOKS.length} books, ${verses.toLocaleString('en-US')} verses. Structure: KJV[bookId][chapter-1][verse-1]. */
const KJV = ${JSON.stringify(out)};
`;
  const dest = path.join(root, 'src/data/kjv.js');
  fs.writeFileSync(dest, body);
  console.log(`wrote ${path.relative(root, dest)} — ${BOOKS.length} books, ${verses} verses, ${(body.length / 1024 / 1024).toFixed(1)}MB`);
})().catch(e => { console.error(e.message); process.exit(1); });
